### ISSUE TITLE
Raspberry Pi Code: Learn how to interact with user list database

### ISSUE THREAD

**Issue by AmmarMohammed01** [UTDallasEPICS/UTDesign-FabLab-Tool-Access#12]
Once the database is setup, the Python code on the Raspberry Pi should be able to grab data from the database to see the list of users. The Python code should also be able to send updates by keeping track of new users added and which users have been removed.

**Comment by AmmarMohammed01** [comment]
Perhaps the program can check for an update in the database each time while loop restarts.

**Comment by AaduMaadu** [comment]
Machine Log Data (webpage)

- [x] Should be able to be sorted by recently used
- [x] Should be able to be downloaded as an excel file

A table displaying: 
- User ID
- Time used
- Machine Type

**Comment by AmmarMohammed01** [comment]
The database has been created to track time usage data
